### ISSUE TITLE
Error while importing another less file within a less file.

### ISSUE THREAD

**Issue by sabbirrahman** [webpack-contrib/less-loader#104]
I'm trying to use less-loader with [Angular Universal Starter](https://github.com/angular/universal-starter). I've installed less & less-loader and added the bellow line in webpack.config.js

```
loaders: [
  ...
  { test: /\.less$/, loaders: ['raw-loader', 'less-loader'] }
  ...
]
```

It works fine If I load a simple less file with variables & mixins. But if I load a less file that imports another less file, I get the following error:

```
MY_PROJECT_DIRECTORY\node_modules\webpack\lib\dependencies\LoaderPlugin.js:34
if(!dep.module._source) throw new Error("The module created for a LoaderDependency must have a property _source");
```

I need to import a less file which will contains some common variables & mixins in almost all of my component's less files. It will be great if anyone can help me out.

**Comment by dottodot** [comment]
I have the same issue, did you manage to work it out?

**Comment by dottodot** [comment]
Out of curiosity I tried an older version of webpack as I was using 2.1.0-beta.20, but on 1.13.1 I'm also getting a error but a different one.

```
/coco-uni/node_modules/webpack-core/lib/LoadersList.js:81
		r.forEach(function(r) {
		  ^

TypeError: r.forEach is not a function
    at /coco-uni/node_modules/webpack-core/lib/LoadersList.js:81:5
    at Array.reduce (native)
    at LoadersList.match (/coco-uni/node_modules/webpack-core/lib/LoadersList.js:80:27)
    at /coco-uni/node_modules/webpack/lib/NormalModuleFactory.js:111:68
    at /coco-uni/node_modules/async/lib/async.js:726:13
    at /coco-uni/node_modules/async/lib/async.js:52:16
    at done (/coco-uni/node_modules/async/lib/async.js:246:17)
    at /coco-uni/node_modules/async/lib/async.js:44:16
    at /coco-uni/node_modules/async/lib/async.js:723:17
    at /coco-uni/node_modules/async/lib/async.js:167:37
    at /coco-uni/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:29:4
    at onResolved (/coco-uni/node_modules/enhanced-resolve/lib/Resolver.js:39:10)
    at /coco-uni/node_modules/enhanced-resolve/lib/Resolver.js:123:21
    at /coco-uni/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/coco-uni/node_modules/enhanced-resolve/lib/Resolver.js:104:30)
    at loggingCallbackWrapper (/coco-uni/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /coco-uni/node_modules/tapable/lib/Tapable.js:134:6
    at innerCallback (/coco-uni/node_modules/enhanced-resolve/lib/Resolver.js:90:37)
    at loggingCallbackWrapper (/coco-uni/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /coco-uni/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/coco-uni/node_modules/enhanced-resolve/lib/ResultSymlinkPlugin.js:39:32)
    at /coco-uni/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /coco-uni/node_modules/enhanced-resolve/lib/ResultSymlinkPlugin.js:36:5
    at Storage.finished (/coco-uni/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by dottodot** [comment]
Any update on what this issue might be. It's currently not possible to use `@import` which defeats the purpose of using less.

It compiles fine in there are no imports

**Comment by paquettea** [comment]
@dottodot are you trying to use it within an angular-universal project ? I saw that you had one repo, and I have the same issue. I'm a beginner with webpack, but I think it could be related to the configuration of angular-universal with webpack

**Comment by dottodot** [comment]
@paquettea yes it was, I ended up giving up and using sass instead which works fine

**Comment by paquettea** [comment]
ok :( thanks for the tip

**Comment by XciA** [comment]
> Any update on what this issue might be. It's currently not possible to use `@import` which defeats the purpose of using less.
> 
> It compiles fine in there are no imports

The statement might be wrong , the purpose of less was to bring modularity which is not possible through css.

**Comment by evilebottnawi** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!
