### ISSUE TITLE
ModuleBuildError: Module build failed: TypeError: Cannot read property 'rules' of undefined

### ISSUE THREAD

**Issue by jhnns** [webpack-contrib/less-loader#14]
Sometimes less dies because of this error

```
Error: Bundle creation failed due to Errors: 
ModuleBuildError: Module build failed: TypeError: Cannot read property 'rules' of undefined
    at Object.tree.Import.eval (/path/to/project/node_modules/less/lib/less/tree/import.js:115:56)
    at Object.tree.Ruleset.evalImports (/path/to/project/node_modules/less/lib/less/tree/ruleset.js:165:40)
    at Object.tree.Import.eval (/path/to/project/node_modules/less/lib/less/tree/import.js:117:21)
    at Object.tree.Ruleset.evalImports (/path/to/project/node_modules/less/lib/less/tree/ruleset.js:165:40)
    at Object.tree.Import.eval (/path/to/project/node_modules/less/lib/less/tree/import.js:117:21)
    at Object.tree.Ruleset.evalImports (/path/to/project/node_modules/less/lib/less/tree/ruleset.js:165:40)
    at Object.tree.Ruleset.eval (/path/to/project/node_modules/less/lib/less/tree/ruleset.js:73:21)
    at Object.toCSS (/path/to/project/node_modules/less/lib/less/parser.js:575:46)
    at /path/to/project/node_modules/less/lib/less/index.js:26:54
    at Object.finish [as _finish] (/path/to/project/node_modules/less/lib/less/parser.js:669:28)
    at Watching.handler (/path/to/project/server/createBundle.js:13:22)
    at Watching._done (/path/to/project/node_modules/webpack/lib/Compiler.js:77:7)
    at Watching.<anonymous> (/path/to/project/node_modules/webpack/lib/Compiler.js:57:18)
    at Tapable.emitRecords (/path/to/project/node_modules/webpack/lib/Compiler.js:263:37)
    at Watching.<anonymous> (/path/to/project/node_modules/webpack/lib/Compiler.js:54:19)
    at /path/to/project/node_modules/webpack/lib/Compiler.js:256:11
    at Tapable.applyPluginsAsync (/path/to/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:48:69)
    at Tapable.afterEmit (/path/to/project/node_modules/webpack/lib/Compiler.js:253:8)
    at Tapable.<anonymous> (/path/to/project/node_modules/webpack/lib/Compiler.js:248:14)
    at /path/to/project/node_modules/webpack/node_modules/async/lib/async.js:119:25
```

I don't have a clue why it happens and it might also be an issue with less, just for the record. It doesn't have to do with a special less syntax because the same module will sometimes trigger this error and sometimes not.

I couldn't find an issue at the less repo so I'm suspecting that a change within https://github.com/webpack/less-loader/commit/087d5236fa96f1622720cc60cd6d19ba0474c18b might trigger it.

**Comment by iamstarkov** [comment]
1 year anniversary

**Comment by jhnns** [comment]
Didn't occur for a while now, so let's close it.
