### ISSUE TITLE
less-plugin-glob plugin cannot be using as option plugin

### ISSUE THREAD

**Issue by SemihGk** [webpack-contrib/less-loader#190]
Hey,

I am trying to use [less-plugin-glob](https://github.com/just-boris/less-plugin-glob) with less loader, but it throws an error: 
```

Module build failed: TypeError: plugin.install is not a function
    at PluginManager.addPlugin (/node_modules/less/lib/less/plugin-manager.js:29:12)
    at PluginManager.addPlugins (/node_modules/less/lib/less/plugin-manager.js:19:18)
    at Object.parse (/node_modules/less/lib/less/parse.js:34:27)
    at Object.render (/node_modules/less/lib/less/render.js:25:18)
    at Object.module.exports.source (/node_modules/less-loader/lib/loader.js:45:10)
```

Here is my config:
```
    ....
           {
                loader: 'less-loader',
                options: {
                    sourceMap: true,
                    plugins: [
                        require('less-plugin-glob')
                    ]
                }
            }
....
```

In the documentation section points that I can use less plugins as an option, but it seems this specific less plugin doesn't work. 

Thank you for any suggestion.

**Comment by coldshine** [comment]
Adding the `paths` option helped me:
```
...
{
    loader: 'less-loader',
    options: {
        paths: [
            path.resolve(path.join(__dirname, 'app'))
        ],
        plugins: [
            require('less-plugin-glob')
        ]
    }
}
```

**Comment by michael-ciniawsky** [comment]
This was an issue with an early version of `less-loader >= v4.0.0` and should be fixed, feel free to reopen if still regressions
