### ISSUE TITLE
Class constructor FileManager cannot be invoked without 'new'.

### ISSUE THREAD

**Issue by ZhiGang-Fang** [webpack-contrib/less-loader#300]
* Operating System:
* Node Version: 10.0.0
* NPM Version: 6.0.0
* webpack Version: 3.0.0
* less-loader Version: 5.0.0

### Code

```js
  // webpack.config.js
  // If your code blocks are over 20 lines, please paste a link to a gist
  // (https://gist.github.com).
```

```js
  // additional code, HEY YO remove this block if you don't need it
```

### How Do We Reproduce?

```
 ERROR in ./src/pages/score/components/current/no-join/index.less
Module build failed (from ./node_modules/_mini-css-extract-plugin@0.5.0@mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js):


Class constructor FileManager cannot be invoked without 'new'
      in undefined (line undefined, column undefined)
    at runLoaders (/home/admin/build/node_modules/_webpack@4.39.2@webpack/lib/NormalModule.js:313:20)
    at /home/admin/build/node_modules/_loader-runner@2.4.0@loader-runner/lib/LoaderRunner.js:367:11
    at /home/admin/build/node_modules/_loader-runner@2.4.0@loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/admin/build/node_modules/_loader-runner@2.4.0@loader-runner/lib/LoaderRunner.js:111:13)
```

**Comment by ZhiGang-Fang** [comment]
This is an issue with an older version of less-loader, not Less, which did not inherit the Less filemanager correctly. less-loader 5.0 does. See

**Comment by abenhamdine** [comment]
This error occurs with less-loader <5.0 (see the stack trace you have paste, which shows less-loader@4.1.0), not with less-loader 5.0.0
