### ISSUE TITLE
can't resolve "*.less"

### ISSUE THREAD

**Issue by videni** [webpack-contrib/less-loader#312]
Please give me a hand, I have spent days on this issue🙏.

## What I have done

1. I have configured `less-loader`
![image](https://user-images.githubusercontent.com/4058341/71146008-81e8a880-225e-11ea-8d47-87fe2aa1419b.png)

## Error
```
[ error ] ./src/components/GlobalHeader/index.less

@import '~antd/es/style/themes/default.less';
^
Can't resolve 'antd/es/style/themes/default.less' in '/Users/vidy/www/acme-admin-ui1/src/components/GlobalHeader'
      in /Users/vidy/www/acme-admin-ui1/src/components/GlobalHeader/index.less (line 1, column 0)
```

## Error details

```
LessError {message: "Can't resolve 'antd/es/style/themes/default.less' …acme-admin-ui1/src/components/HeaderDropdown'", stack: "Error: Can't resolve 'antd/es/style/themes/default…de_modules/enhanced-resolve/lib/Resolver.js:285:5", type: "Syntax", filename: "/Users/vidy/www/acme-admin-ui1/src/components/HeaderDropdown/index.less", index: 0, …}
callExtract: undefined
callLine: NaN
column: 0
extract: (3) [undefined, "@import '~antd/es/style/themes/default.less';", ""]
filename: "/Users/vidy/www/acme-admin-ui1/src/components/HeaderDropdown/index.less"
hideStack: true
index: 0
line: 1
message: "↵↵@import '~antd/es/style/themes/default.less';↵^↵Can't resolve 'antd/es/style/themes/default.less' in '/Users/vidy/www/acme-admin-ui1/src/components/HeaderDropdown'↵      in /Users/vidy/www/acme-admin-ui1/src/components/HeaderDropdown/index.less (line 1, column 0)"
stack: "Error: Can't resolve 'antd/es/style/themes/default.less' in '/Users/vidy/www/acme-admin-ui1/src/components/HeaderDropdown'↵    at /Users/vidy/www/acme-admin-ui1/node_modules/enhanced-resolve/lib/Resolver.js:209:21↵    at /Users/vidy/www/acme-admin-ui1/node_modules/enhanced-resolve/lib/Resolver.js:285:5↵    at eval (eval at create (/Users/vidy/www/acme-admin-ui1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)↵    at /Users/vidy/www/acme-admin-ui1/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7↵    at /Users/vidy/www/acme-admin-ui1/node_modules/enhanced-resolve/lib/Resolver.js:285:5↵    at eval (eval at create (/Users/vidy/www/acme-admin-ui1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)↵    at /Users/vidy/www/acme-admin-ui1/node_modules/enhanced-resolve/lib/Resolver.js:285:5↵    at eval (eval at create (/Users/vidy/www/acme-admin-ui1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)↵    at /Users/vidy/www/acme-admin-ui1/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43↵    at /Users/vidy/www/acme-admin-ui1/node_modules/enhanced-resolve/lib/Resolver.js:285:5↵    at eval (eval at create (/Users/vidy/www/acme-admin-ui1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:657:1)↵    at /Users/vidy/www/acme-admin-ui1/node_modules/enhanced-resolve/lib/AliasPlugin.js:67:43↵    at /Users/vidy/www/acme-admin-ui1/node_modules/enhanced-resolve/lib/Resolver.js:285:5↵    at eval (eval at create (/Users/vidy/www/acme-admin-ui1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)↵    at /Users/vidy/www/acme-admin-ui1/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7↵    at /Users/vidy/www/acme-admin-ui1/node_modules/enhanced-resolve/lib/Resolver.js:285:5"
type: "Syntax"

```

### I am using less-loader 4
>Starting with less-loader 4, you can now choose between Less' builtin resolver and webpack's resolver. By default, webpack's resolver is used.

but  where is the `~` defined  in webpack?

yarn list | grep less-loader
```
│  └─ less-loader@4.1.0
├─ less-loader@4.1.0
```
### file exists
 ll node_modules/antd/es/style/themes/default.less
```
-rw-r--r--  1 vidy  staff    20K Oct 26  1985 node_modules/antd/es/style/themes/default.less
```

**Comment by anikethsaha** [comment]
Is the file present in the mentioned path ?

**Comment by videni** [comment]
@anikethsaha , yes,

 ll node_modules/antd/es/style/themes/default.less
```
-rw-r--r--  1 vidy  staff    20K Oct 26  1985 node_modules/antd/es/style/themes/default.less
```

**Comment by anikethsaha** [comment]
You have any reproducible repo ? maybe something is buggy in the config

**Comment by anikethsaha** [comment]
Better if you can create a sandbox, easier to work on

**Comment by videni** [comment]
@anikethsaha, somehow it works now, I don't know why I will figure out later,  thanks you.
