### ISSUE TITLE
less-loader is not working

### ISSUE THREAD

**Issue by ameyzulkanthiwar** [webpack-contrib/less-loader#313]
Hello, Guys, I am new to webpack and trying to add the loader for the '.less' file but getting an error.

```
ERROR in ./node_modules/@ivoyant/component-array-template/dist/styles.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js!./node_modules/@ivoyant/component-array-template/dist/styles.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):
Error: Cannot find module 'less'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\less-loader\dist\index.js:8:36)
    at Module._compile (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\less-loader\dist\cjs.js:3:18)
    at Module._compile (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at loadLoader (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\loader-runner\lib\loadLoader.js:18:17)
    at iteratePitchingLoaders (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\loader-runner\lib\LoaderRunner.js:176:18
    at loadLoader (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\loader-runner\lib\loadLoader.js:47:3)
    at iteratePitchingLoaders (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\webpack\lib\NormalModule.js:295:3)
    at NormalModule.build (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\webpack\lib\NormalModule.js:446:15)
    at Compilation.buildModule (C:\Users\ivoyant-amey\Desktop\webpack\new-dashboard-viewer\node_modules\webpack\lib\Compilation.js:739:10)
 @ ./node_modules/@ivoyant/component-array-template/dist/styles.less 2:26-117
 @ ./node_modules/@ivoyant/component-array-template/dist/arrayTemplate.js
 @ ./node_modules/@ivoyant/component-array-template/dist/index.js
 @ ./node_modules sync @ivoyant\/[\w+\-0-9]+\/(dist\/index\.js$|package.json$|icon)
 @ ./src/components/Library.js
 @ ./src/components/ComponentCard.js
 @ ./src/containers/Layout.js
 @ ./src/app.js
 @ ./src/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! dashboard-viewer@1.0.0 build-dev: `webpack --config webpack.dev.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the dashboard-viewer@1.0.0 build-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ivoyant-amey\AppData\Roaming\npm-cache\_logs\2020-01-07T20_35_08_177Z-debug.log
```
webpack.dev.config.js
```
 {
            test: /\.less$/,
            use: [
                'style-loader',
                'css-loader',
                {
                    loader: "less-loader", 
                    options: {
                           paths: [
                                 path.resolve(__dirname, "node_modules")
                            ],
                      }
                  },
            ],
        },
```

NOTE: I tried without option attribute.

Even I don't know this question is valid or not because I saw so many people having trouble with this and could not able to find working solution.

Thank you.

**Comment by ameyzulkanthiwar** [comment]
Thank you guys I get the solution for this error 

```
npm install --save-dev less
```

along with less-loader, we need less module to it's an internal dependency I think.

Thank you.
